//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalSBP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<bool> SuccessfulLogin { get; set; }
        public string Login { get; set; }
    
        public virtual Emploee Emploee { get; set; }
    }
}
