//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalSBP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ServicesOrders = new HashSet<ServicesOrder>();
        }
    
        public int Id { get; set; }
        public string CodeOrder { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.TimeSpan> TimeOrder { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<int> Id_OrderStatus { get; set; }
        public Nullable<System.DateTime> DateClosing { get; set; }
        public Nullable<double> TimeRental { get; set; }
        public Nullable<int> Id_Creator_Employee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Emploee Emploee { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesOrder> ServicesOrders { get; set; }
    }
}
